//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM-Beziehungsmetadaten

[assembly: EdmRelationshipAttribute("MoviesModel", "FK_GenreMovie", "Genres", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(MovieManager.Genre), "Movies", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MovieManager.Movie), true)]

#endregion

namespace MovieManager
{
    #region Kontexte
    
    /// <summary>
    /// Keine Dokumentation für Metadaten verfügbar.
    /// </summary>
    public partial class MovieEntities : ObjectContext
    {
        #region Konstruktoren
    
        /// <summary>
        /// Initialisiert ein neues MovieEntities-Objekt mithilfe der in Abschnitt 'MovieEntities' der Anwendungskonfigurationsdatei gefundenen Verbindungszeichenfolge.
        /// </summary>
        public MovieEntities() : base("name=MovieEntities", "MovieEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialisiert ein neues MovieEntities-Objekt.
        /// </summary>
        public MovieEntities(string connectionString) : base(connectionString, "MovieEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialisiert ein neues MovieEntities-Objekt.
        /// </summary>
        public MovieEntities(EntityConnection connection) : base(connection, "MovieEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partielle Methoden
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet-Eigenschaften
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        public ObjectSet<Genre> Genres
        {
            get
            {
                if ((_Genres == null))
                {
                    _Genres = base.CreateObjectSet<Genre>("Genres");
                }
                return _Genres;
            }
        }
        private ObjectSet<Genre> _Genres;
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        public ObjectSet<Movie> Movies
        {
            get
            {
                if ((_Movies == null))
                {
                    _Movies = base.CreateObjectSet<Movie>("Movies");
                }
                return _Movies;
            }
        }
        private ObjectSet<Movie> _Movies;

        #endregion
        #region AddTo-Methoden
    
        /// <summary>
        /// Veraltete Methode zum Hinzufügen eines neuen Objekts zum EntitySet 'Genres'. Verwenden Sie stattdessen die Methode '.Add' der zugeordneten Eigenschaft 'ObjectSet&lt;T&gt;'.
        /// </summary>
        public void AddToGenres(Genre genre)
        {
            base.AddObject("Genres", genre);
        }
    
        /// <summary>
        /// Veraltete Methode zum Hinzufügen eines neuen Objekts zum EntitySet 'Movies'. Verwenden Sie stattdessen die Methode '.Add' der zugeordneten Eigenschaft 'ObjectSet&lt;T&gt;'.
        /// </summary>
        public void AddToMovies(Movie movie)
        {
            base.AddObject("Movies", movie);
        }

        #endregion
    }
    

    #endregion
    
    #region Entitäten
    
    /// <summary>
    /// Keine Dokumentation für Metadaten verfügbar.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MoviesModel", Name="Genre")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Genre : EntityObject
    {
        #region Factory-Methode
    
        /// <summary>
        /// Erstellt ein neues Genre-Objekt.
        /// </summary>
        /// <param name="id">Anfangswert der Eigenschaft ID.</param>
        /// <param name="name">Anfangswert der Eigenschaft Name.</param>
        /// <param name="bild">Anfangswert der Eigenschaft Bild.</param>
        public static Genre CreateGenre(global::System.Int32 id, global::System.String name, global::System.String bild)
        {
            Genre genre = new Genre();
            genre.ID = id;
            genre.Name = name;
            genre.Bild = bild;
            return genre;
        }

        #endregion
        #region Primitive Eigenschaften
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Bild
        {
            get
            {
                return _Bild;
            }
            set
            {
                OnBildChanging(value);
                ReportPropertyChanging("Bild");
                _Bild = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Bild");
                OnBildChanged();
            }
        }
        private global::System.String _Bild;
        partial void OnBildChanging(global::System.String value);
        partial void OnBildChanged();

        #endregion
    
        #region Navigationseigenschaften
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MoviesModel", "FK_GenreMovie", "Movies")]
        public EntityCollection<Movie> Movies
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Movie>("MoviesModel.FK_GenreMovie", "Movies");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Movie>("MoviesModel.FK_GenreMovie", "Movies", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// Keine Dokumentation für Metadaten verfügbar.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MoviesModel", Name="Movie")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Movie : EntityObject
    {
        #region Factory-Methode
    
        /// <summary>
        /// Erstellt ein neues Movie-Objekt.
        /// </summary>
        /// <param name="id">Anfangswert der Eigenschaft ID.</param>
        /// <param name="pfad">Anfangswert der Eigenschaft Pfad.</param>
        /// <param name="titel">Anfangswert der Eigenschaft Titel.</param>
        /// <param name="breite">Anfangswert der Eigenschaft Breite.</param>
        /// <param name="hohe">Anfangswert der Eigenschaft Hohe.</param>
        public static Movie CreateMovie(global::System.Int32 id, global::System.String pfad, global::System.String titel, global::System.Int32 breite, global::System.Int32 hohe)
        {
            Movie movie = new Movie();
            movie.ID = id;
            movie.Pfad = pfad;
            movie.Titel = titel;
            movie.Breite = breite;
            movie.Hohe = hohe;
            return movie;
        }

        #endregion
        #region Primitive Eigenschaften
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Pfad
        {
            get
            {
                return _Pfad;
            }
            set
            {
                OnPfadChanging(value);
                ReportPropertyChanging("Pfad");
                _Pfad = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Pfad");
                OnPfadChanged();
            }
        }
        private global::System.String _Pfad;
        partial void OnPfadChanging(global::System.String value);
        partial void OnPfadChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Titel
        {
            get
            {
                return _Titel;
            }
            set
            {
                OnTitelChanging(value);
                ReportPropertyChanging("Titel");
                _Titel = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Titel");
                OnTitelChanged();
            }
        }
        private global::System.String _Titel;
        partial void OnTitelChanging(global::System.String value);
        partial void OnTitelChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Lange
        {
            get
            {
                return _Lange;
            }
            set
            {
                OnLangeChanging(value);
                ReportPropertyChanging("Lange");
                _Lange = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Lange");
                OnLangeChanged();
            }
        }
        private global::System.String _Lange;
        partial void OnLangeChanging(global::System.String value);
        partial void OnLangeChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Stichworte
        {
            get
            {
                return _Stichworte;
            }
            set
            {
                OnStichworteChanging(value);
                ReportPropertyChanging("Stichworte");
                _Stichworte = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Stichworte");
                OnStichworteChanged();
            }
        }
        private global::System.String _Stichworte;
        partial void OnStichworteChanging(global::System.String value);
        partial void OnStichworteChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Inhalt
        {
            get
            {
                return _Inhalt;
            }
            set
            {
                OnInhaltChanging(value);
                ReportPropertyChanging("Inhalt");
                _Inhalt = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Inhalt");
                OnInhaltChanged();
            }
        }
        private global::System.String _Inhalt;
        partial void OnInhaltChanging(global::System.String value);
        partial void OnInhaltChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Bild
        {
            get
            {
                return _Bild;
            }
            set
            {
                OnBildChanging(value);
                ReportPropertyChanging("Bild");
                _Bild = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Bild");
                OnBildChanged();
            }
        }
        private global::System.String _Bild;
        partial void OnBildChanging(global::System.String value);
        partial void OnBildChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> Grose
        {
            get
            {
                return _Grose;
            }
            set
            {
                OnGroseChanging(value);
                ReportPropertyChanging("Grose");
                _Grose = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Grose");
                OnGroseChanged();
            }
        }
        private Nullable<global::System.Int64> _Grose;
        partial void OnGroseChanging(Nullable<global::System.Int64> value);
        partial void OnGroseChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> GenreID
        {
            get
            {
                return _GenreID;
            }
            set
            {
                OnGenreIDChanging(value);
                ReportPropertyChanging("GenreID");
                _GenreID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("GenreID");
                OnGenreIDChanged();
            }
        }
        private Nullable<global::System.Int32> _GenreID;
        partial void OnGenreIDChanging(Nullable<global::System.Int32> value);
        partial void OnGenreIDChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Breite
        {
            get
            {
                return _Breite;
            }
            set
            {
                OnBreiteChanging(value);
                ReportPropertyChanging("Breite");
                _Breite = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Breite");
                OnBreiteChanged();
            }
        }
        private global::System.Int32 _Breite;
        partial void OnBreiteChanging(global::System.Int32 value);
        partial void OnBreiteChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Hohe
        {
            get
            {
                return _Hohe;
            }
            set
            {
                OnHoheChanging(value);
                ReportPropertyChanging("Hohe");
                _Hohe = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Hohe");
                OnHoheChanged();
            }
        }
        private global::System.Int32 _Hohe;
        partial void OnHoheChanging(global::System.Int32 value);
        partial void OnHoheChanged();

        #endregion
    
        #region Navigationseigenschaften
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MoviesModel", "FK_GenreMovie", "Genres")]
        public Genre Genre
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Genre>("MoviesModel.FK_GenreMovie", "Genres").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Genre>("MoviesModel.FK_GenreMovie", "Genres").Value = value;
            }
        }
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Genre> GenreReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Genre>("MoviesModel.FK_GenreMovie", "Genres");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Genre>("MoviesModel.FK_GenreMovie", "Genres", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
